package net.jangaroo.jooc.mvnplugin;

@SuppressWarnings("FieldCanBeLocal")
public class SenchaConfiguration extends SenchaProfileConfiguration {

  public enum Type {
    CODE,
    THEME,
    APP,
    WORKSPACE
  }

  /**
   * Set this to <code>true</code> to generate sencha files (workspace, package, app).
   *
   * @parameter default-value="false"
   */
  private boolean enabled = false;

  /**
   * Adjust the sencha type generated by the plugin.
   *
   * @parameter default-value="CODE"
   */
  private Type type = Type.CODE;

  /**
   * The toolkit to use
   *
   * @parameter default-value="classic"
   */
  private String toolkit = "classic";

  /**
   * The theme to use
   *
   * @parameter default-value="theme-neptune"
   */
  private String theme = "theme-neptune";

  /**
   * @parameter default-value="${production}"
   */
  private SenchaProfileConfiguration production;

  /**
   * @parameter default-value="${development}"
   */
  private SenchaProfileConfiguration development;

  /**
   * @parameter default-value="${testing}"
   */
  private SenchaProfileConfiguration testing;

  public boolean isEnabled() {
    return enabled;
  }

  public Type getType() {
    return type;
  }

  public String getToolkit() {
    return toolkit;
  }

  public String getTheme() {
    return theme;
  }

  public SenchaProfileConfiguration getProduction() {
    return production;
  }

  public SenchaProfileConfiguration getDevelopment() {
    return development;
  }

  public SenchaProfileConfiguration getTesting() {
    return testing;
  }
}
