package net.jangaroo.jooc.mvnplugin;

@SuppressWarnings("FieldCanBeLocal")
public class SenchaConfiguration extends SenchaProfileConfiguration {

  public enum Type {
    CODE,
    THEME,
    APP,
    WORKSPACE
  }

  /**
   * Set this to <code>true</code> to generate sencha files (workspace, package, app).
   *
   * @parameter default-value="false"
   */
  private boolean enabled = false;

  /**
   * Adjust the sencha type generated by the plugin.
   *
   * @parameter default-value="CODE"
   */
  private Type type = Type.CODE;

  /**
   * The toolkit to use
   *
   * @parameter default-value="classic"
   */
  private String toolkit = "classic";

  /**
   * The theme to use
   *
   * @parameter default-value=""
   */
  private String theme = "";

  /**
   * @parameter default-value="${production}"
   */
  private SenchaProfileConfiguration production;

  /**
   * @parameter default-value="${development}"
   */
  private SenchaProfileConfiguration development;

  /**
   * @parameter default-value="${testing}"
   */
  private SenchaProfileConfiguration testing;

  /**
   * Output directory for the module.
   *
   * @parameter default-value="${project.build.directory}/sencha"
   */
  private String baseDir;

  /**
   * Ext Framework directory for the module.
   *
   * @parameter default-value="ext"
   */
  private String extFrameworkDir="ext";

  /**
   * Build directory relative to baseDir
   *
   * @parameter default-value="build"
   */
  private String buildDir="build";

  /**
   * Packages directory relative to baseDir
   *
   * @parameter default-value="packages"
   */
  private String packagesDir="packages";

  public boolean isEnabled() {
    return enabled;
  }

  public Type getType() {
    return type;
  }

  public String getToolkit() {
    return toolkit;
  }

  public String getTheme() {
    return theme;
  }

  public SenchaProfileConfiguration getProduction() {
    return production;
  }

  public SenchaProfileConfiguration getDevelopment() {
    return development;
  }

  public SenchaProfileConfiguration getTesting() {
    return testing;
  }

  public String getBaseDir() {
    return baseDir;
  }

  public String getBuildDir() {
    return buildDir;
  }

  public String getPackagesDir() {
    return packagesDir;
  }

  public String getExtFrameworkDir() {
    return extFrameworkDir;
  }
}
